name: Deploy on Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: jorge2017
          heroku_app_name: "coffaine-deliveries"
          heroku_email: jorgechucena@gmail.com
          usedocker: true
